spring:
  application:
    name: integration-test-demo
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
  flyway:
    locations: classpath:/db/migration
    enabled: false

sqs:
  userCreated:
    name: user-created.fifo
  documentUploadCompleted:
    name: document-upload-completed.fifo
  notification:
    name: notifications.fifo
  message:
    batch:
      max: 10
  backOffMills: 10000

s3:
  userDocuments:
    bucketName: user-documents
